#!/bin/bash

if [ $# -eq 0 ]; then
  echo -n "Note name: "
  read note_name
else
  note_name=$1
fi

mkdir "$note_name"
mkdir "$note_name/assets"
touch "$note_name/assets/main.c"
ln -fs ../../../dependencies/makefile "$note_name/assets/makefile"
touch "$note_name/$note_name.md"
