#!/bin/bash

# sed 's/^# /\\newpage\n# /' $1 | pandoc -o $2 --pdf-engine=xelatex -f markdown

out="$(basename "${1%.md}.pdf")"

sed 's/^## /\\newpage\n## /' $1 | pandoc -o $out --pdf-engine=xelatex -f markdown
