#!/bin/bash

# Download valgrind file
docker pull karek/valgrind && clear

# Enter the docker container with the build dir
docker run --rm -v $(pwd):/app jaco8oneill/valgrind sh -c "cd /app; make clean; make CC=gcc CFLAGS='-g -Wall -Wextra' && clear; valgrind --leak-check=full $1"
