DROP TABLE IF EXISTS registrations;

CREATE TABLE registrations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  sport TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
